### ISSUE TITLE
Build Failed: NPM Failed: npm ERR! package.json requires a "name" field

### ISSUE THREAD

**Issue by webappvicio** [stackery/react-single-page#1]
I tried to deploy, but I got this error: 

[sam build --template .stackery/template.yaml --region ap-southeast-1 --base-dir .]
Building Functions...

	SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

2019-09-09 12:39:42 Building resource 'function5B4675E7'
2019-09-09 12:39:42 Running NodejsNpmBuilder:NpmPack

Build Failed
**Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! package.json requires a "name" field**

**Comment by txase** [comment]
Hi @webappvicio!

Thanks for reporting this! We forgot to update the package.json to ensure it works correctly with the latest AWS SAM CLI mechanisms for building node.js functions. I just updated the package.json to add `name` and `version` fields (commit 6e517cf7e1d6bd33092d6f54e5f1c7c3a25cdcef). This should now deploy correctly!

Thanks for reporting this issue!
